### PR TITLE
Message Counts

### PR DESCRIPTION
**Pull request by vveljko**
Message Counts API

### CODE REVIEW

**Comment by madisonsmith** [comment]
@vveljko this looks good to me! Is travis just being annoying with the build?

**Comment by mrtryhard** [comment]
> @vveljko this looks good to me! Is travis just being annoying with the build?

It seems [some tests cases fails](https://travis-ci.com/pubnub/c-core/jobs/182916452).

**Comment by vveljko** [comment]
@madisonsmith For some reason, the functional test on the "branch build" sometimes hangs, but not on the PR (the virtual branch). Not really sure why is that and is it a problem on Travis or on our side... But it certainly isn't caused by any of these changes.

**Comment by madisonsmith** [comment]
@vveljko okay! I've restarted it a couple times without success. I'm seeing this https://travis-ci.com/pubnub/c-core/jobs/182916453

**Comment by vveljko** [comment]
@madisonsmith It's some transient networking/overload issue, somehow related to Travis Linux. It _never_ fails on Mac and also doesn't fail in times of low traffic on Linux either. We'll get to the bottom of this, but, as far as this PR is concerned, it has nothing to do with it and PR can be merged.

**Pull request merged**
