### PR TITLE
Fixes for `windows.mk` openssl makefile `CLEN-2403`

### PR DESCRIPTION
**Pull request by stephenlb**
feat(custom-flags): added the way to set additional compiler flags

Additional flags for C/CPP can be set with: `USER_C_FLAGS` / `USER_CXX_FLAGS`

fix(Makefile): fix missed `pbbase64.c`

Fix because of which one of the source files has been missed for Windows.

fix(Makefile): fix Makefile macro for Windows

Fix issue with unsupported concatenation of sources files / definitions (`+=`).

refactor(makefiles): refactor Makefiles 

Refactor our `Makefiles` from different folders and platforms to use `include` directives to include shared definitions, flags, source files.

### CODE REVIEW

**Review by parfeon — APPROVED** [review]
LGTM!

**Comment by parfeon** [comment]
@stephenlb I need to change PR description, so I'm keeping your original message here:

> Update `windows.mk` makefile in openssl builds.
>
> - [x] Adds `$(APP_CFLAGS)` to `CFLAGS`
> - [x] Adds `..\lib\base64\pbbase64.c` to `windows.mk` makefile
> - [x] Removes `+=` operators, which are not always supported windows.mk makefile
> 
> Jira Ticket: https://pubnub.atlassian.net/browse/CLEN-2403

**Comment by stephenlb** [comment]
Sounds good!

**Comment by parfeon** [comment]
@pubnub-release-bot release

**Pull request merged**
